# v6_prj - V6 Project object 
Import('v6_prj')

import os

v6_prj.name     = 'ciotry'
v6_prj.linkopt  = '--code-loc 0x5A80 --data-loc 0'
v6_prj.stack    = '0xffff'
# v6_prj.heapsize = '0'     # uncomment this line, if you realy need a heap


# In this project we need only sdcc environment  (to compile C source files)
env = v6_prj.env


# generate .c file , from all *.ci files
game_c = env.Command('game.c', Glob('*.ci') + ['platform/platform_v6z80p.ci'], "cito -l c -o $TARGET  $SOURCES" +
" && " + v6_prj.basedir + "src/ciotry/change_text.php $TARGET")
game_c[0].my_progress_message = '------------- Generate C file  from CIO files ---------'

# compile user .c files to object files
objs = env.Object(   ['host.c'], 
                CCFLAGS     = env['CCFLAGS']           + ['--std-sdcc99', '--opt-code-speed'],  
                CPPDEFINES  = env['CPPDEFINES']        + [{'OWN_SP' : v6_prj.stack}]
                )

# here, for some reason, the scons cant make auto depend 
# so? we need to set depend manualy
env.Depends(objs, game_c)

# link to .ihx and convert .ihx to .exe
final_exe = v6_prj.FLOS_Program(objs)


v6_prj.Upload(final_exe)




# propagate PATH to external commands env
# (thus, program 'cito' will be finded in a PATH dirs)
env['ENV']['PATH'] = os.environ['PATH']
