SHELL = cmd.exe

#
# ZDS II Make File - test_audio project, Debug configuration
#
# Generated by: ZDS II - eZ80Acclaim! 5.1.1 (Build 10061702)
#   IDE component: d:5.1:10042301
#   Install Path: C:\Program Files\ZiLOG\ZDSII_eZ80Acclaim!_5.1.1\
#

RM = del

ZDS = C:\PROGRA~1\ZiLOG\ZDSII_~1.1
BIN = $(ZDS)\bin
# ZDS include base directory
INCLUDE = C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include
# intermediate files directory
WORKDIR = E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\AUDIO_~1\Debug

CC = @$(BIN)\eZ80cc
AS = @$(BIN)\eZ80asm
LD = @$(BIN)\eZ80link
AR = @$(BIN)\eZ80lib
WEBTOC = @$(BIN)\mkwebpage

ASFLAGS =  \
-define:_EZ80=1 -define:_SIMULATE=1  \
-include:"E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\AUDIO_~1;..\..\includes;$(INCLUDE)\std;$(INCLUDE)\zilog"  \
-list -NOlistmac -name -pagelen:56 -pagewidth:80 -quiet -sdiopt  \
-warn -debug -NOigcase -cpu:eZ80L92

LDFLAGS = @.\test_audio_Debug.linkcmd
OUTDIR = E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\AUDIO_~1\Debug

build: test_audio

buildall: clean test_audio

relink: deltarget test_audio

deltarget: 
	@if exist $(WORKDIR)\test_audio.lod  \
            $(RM) $(WORKDIR)\test_audio.lod
	@if exist $(WORKDIR)\test_audio.hex  \
            $(RM) $(WORKDIR)\test_audio.hex
	@if exist $(WORKDIR)\test_audio.map  \
            $(RM) $(WORKDIR)\test_audio.map

clean: 
	@if exist $(WORKDIR)\test_audio.lod  \
            $(RM) $(WORKDIR)\test_audio.lod
	@if exist $(WORKDIR)\test_audio.hex  \
            $(RM) $(WORKDIR)\test_audio.hex
	@if exist $(WORKDIR)\test_audio.map  \
            $(RM) $(WORKDIR)\test_audio.map
	@if exist $(WORKDIR)\mix_test.obj  \
            $(RM) $(WORKDIR)\mix_test.obj

# pre-4.11.0 compatibility
rebuildall: buildall 

LIBS = 

OBJS =  \
            $(WORKDIR)\mix_test.obj

test_audio: $(OBJS)
	 $(LD) $(LDFLAGS)

$(WORKDIR)\mix_test.obj :  \
            E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\AUDIO_~1\src\mix_test.asm
	 $(AS) $(ASFLAGS) E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\AUDIO_~1\src\mix_test.asm

