SHELL = cmd.exe

#
# ZDS II Make File - sprite_test project, Debug configuration
#
# Generated by: ZDS II - eZ80Acclaim! 5.1.1 (Build 10061702)
#   IDE component: d:5.1:10042301
#   Install Path: C:\Program Files\ZiLOG\ZDSII_eZ80Acclaim!_5.1.1\
#

RM = del

ZDS = C:\PROGRA~1\ZiLOG\ZDSII_~1.1
BIN = $(ZDS)\bin
# ZDS include base directory
INCLUDE = C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include
# intermediate files directory
WORKDIR = E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\Sprites\Debug

CC = @$(BIN)\eZ80cc
AS = @$(BIN)\eZ80asm
LD = @$(BIN)\eZ80link
AR = @$(BIN)\eZ80lib
WEBTOC = @$(BIN)\mkwebpage

ASFLAGS =  \
-define:_EZ80=1 -define:_SIMULATE=1  \
-include:"E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\Sprites;..\..\includes;$(INCLUDE)\std;$(INCLUDE)\zilog"  \
-list -NOlistmac -name -pagelen:56 -pagewidth:80 -quiet -sdiopt  \
-warn -debug -NOigcase -cpu:eZ80L92

LDFLAGS = @.\sprite_test_Debug.linkcmd
OUTDIR = E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\Sprites\Debug

build: sprite_test

buildall: clean sprite_test

relink: deltarget sprite_test

deltarget: 
	@if exist $(WORKDIR)\sprite_test.lod  \
            $(RM) $(WORKDIR)\sprite_test.lod
	@if exist $(WORKDIR)\sprite_test.hex  \
            $(RM) $(WORKDIR)\sprite_test.hex
	@if exist $(WORKDIR)\sprite_test.map  \
            $(RM) $(WORKDIR)\sprite_test.map

clean: 
	@if exist $(WORKDIR)\sprite_test.lod  \
            $(RM) $(WORKDIR)\sprite_test.lod
	@if exist $(WORKDIR)\sprite_test.hex  \
            $(RM) $(WORKDIR)\sprite_test.hex
	@if exist $(WORKDIR)\sprite_test.map  \
            $(RM) $(WORKDIR)\sprite_test.map
	@if exist $(WORKDIR)\test2.obj  \
            $(RM) $(WORKDIR)\test2.obj

# pre-4.11.0 compatibility
rebuildall: buildall 

LIBS = 

OBJS =  \
            $(WORKDIR)\test2.obj

sprite_test: $(OBJS)
	 $(LD) $(LDFLAGS)

$(WORKDIR)\test2.obj :  \
            E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\Sprites\src\test2.asm
	 $(AS) $(ASFLAGS) E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\Sprites\src\test2.asm

