SHELL = cmd.exe

#
# ZDS II Make File - tiletest project, Debug configuration
#
# Generated by: ZDS II - eZ80Acclaim! 5.1.1 (Build 10061702)
#   IDE component: d:5.1:10042301
#   Install Path: C:\Program Files\ZiLOG\ZDSII_eZ80Acclaim!_5.1.1\
#

RM = del

ZDS = C:\PROGRA~1\ZiLOG\ZDSII_~1.1
BIN = $(ZDS)\bin
# ZDS include base directory
INCLUDE = C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include
# intermediate files directory
WORKDIR = E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\tilemap\Debug

CC = @$(BIN)\eZ80cc
AS = @$(BIN)\eZ80asm
LD = @$(BIN)\eZ80link
AR = @$(BIN)\eZ80lib
WEBTOC = @$(BIN)\mkwebpage

ASFLAGS =  \
-define:_EZ80=1 -define:_SIMULATE=1  \
-include:"E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\tilemap;..\..\includes;$(INCLUDE)\std;$(INCLUDE)\zilog"  \
-list -NOlistmac -name -pagelen:56 -pagewidth:80 -quiet -sdiopt  \
-warn -debug -NOigcase -cpu:eZ80L92

LDFLAGS = @.\tiletest_Debug.linkcmd
OUTDIR = E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\tilemap\Debug

build: tiletest

buildall: clean tiletest

relink: deltarget tiletest

deltarget: 
	@if exist $(WORKDIR)\tiletest.lod  \
            $(RM) $(WORKDIR)\tiletest.lod
	@if exist $(WORKDIR)\tiletest.hex  \
            $(RM) $(WORKDIR)\tiletest.hex
	@if exist $(WORKDIR)\tiletest.map  \
            $(RM) $(WORKDIR)\tiletest.map

clean: 
	@if exist $(WORKDIR)\tiletest.lod  \
            $(RM) $(WORKDIR)\tiletest.lod
	@if exist $(WORKDIR)\tiletest.hex  \
            $(RM) $(WORKDIR)\tiletest.hex
	@if exist $(WORKDIR)\tiletest.map  \
            $(RM) $(WORKDIR)\tiletest.map
	@if exist $(WORKDIR)\test4.obj  \
            $(RM) $(WORKDIR)\test4.obj

# pre-4.11.0 compatibility
rebuildall: buildall 

LIBS = 

OBJS =  \
            $(WORKDIR)\test4.obj

tiletest: $(OBJS)
	 $(LD) $(LDFLAGS)

$(WORKDIR)\test4.obj :  \
            E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\tilemap\src\test4.asm
	 $(AS) $(ASFLAGS) E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\tilemap\src\test4.asm

