SHELL = cmd.exe

#
# ZDS II Make File - adl_protracker project, Debug configuration
#
# Generated by: ZDS II - eZ80Acclaim! 5.1.1 (Build 10061702)
#   IDE component: d:5.1:10042301
#   Install Path: C:\Program Files\ZiLOG\ZDSII_eZ80Acclaim!_5.1.1\
#

RM = del

ZDS = C:\PROGRA~1\ZiLOG\ZDSII_~1.1
BIN = $(ZDS)\bin
# ZDS include base directory
INCLUDE = C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include
# intermediate files directory
WORKDIR = E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\PROTRA~1\Debug

CC = @$(BIN)\eZ80cc
AS = @$(BIN)\eZ80asm
LD = @$(BIN)\eZ80link
AR = @$(BIN)\eZ80lib
WEBTOC = @$(BIN)\mkwebpage

ASFLAGS =  \
-define:_EZ80=1 -define:_SIMULATE=1  \
-include:"E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\PROTRA~1;..\..\includes;$(INCLUDE)\std;$(INCLUDE)\zilog"  \
-list -NOlistmac -name -pagelen:56 -pagewidth:80 -quiet -sdiopt  \
-warn -debug -NOigcase -cpu:eZ80L92

LDFLAGS = @.\adl_protracker_Debug.linkcmd
OUTDIR = E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\PROTRA~1\Debug

build: adl_protracker

buildall: clean adl_protracker

relink: deltarget adl_protracker

deltarget: 
	@if exist $(WORKDIR)\adl_protracker.lod  \
            $(RM) $(WORKDIR)\adl_protracker.lod
	@if exist $(WORKDIR)\adl_protracker.hex  \
            $(RM) $(WORKDIR)\adl_protracker.hex
	@if exist $(WORKDIR)\adl_protracker.map  \
            $(RM) $(WORKDIR)\adl_protracker.map

clean: 
	@if exist $(WORKDIR)\adl_protracker.lod  \
            $(RM) $(WORKDIR)\adl_protracker.lod
	@if exist $(WORKDIR)\adl_protracker.hex  \
            $(RM) $(WORKDIR)\adl_protracker.hex
	@if exist $(WORKDIR)\adl_protracker.map  \
            $(RM) $(WORKDIR)\adl_protracker.map
	@if exist $(WORKDIR)\play_interference.obj  \
            $(RM) $(WORKDIR)\play_interference.obj

# pre-4.11.0 compatibility
rebuildall: buildall 

LIBS = 

OBJS =  \
            $(WORKDIR)\play_interference.obj

adl_protracker: $(OBJS)
	 $(LD) $(LDFLAGS)

$(WORKDIR)\play_interference.obj :  \
            E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\PROTRA~1\src\play_interference.asm  \
            E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\PROTRA~1\src\ADL_mode_Protracker_Player_v100.asm  \
            E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\PROTRA~1\src\ADL_mode_Protracker_to_EZ80P_audio.asm  \
            E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\PROTRA~1\src\interference_pattern.asm
	 $(AS) $(ASFLAGS) E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\PROTRA~1\src\play_interference.asm

