# This is main scons (python) script.
# There are 2 targets supported:
#   v6z80p - the default target  (no cmd line options is need)
#   pc - cmd line option is 'target=pc'
#
# When scons is started, it will  search, in current dir, for a file 'SConstruct'
# and execute it.
# Valen 2009-2014

import os
from  v6_project import V6_Project
from  pc_project import PC_Project
from  project_helper import Project_Helper


if Project_Helper.Is_Target_PC():
    print "*** Build for PC ..."
    pc_prj = PC_Project()
    pc_prj.SetupEnv()
    variantBaseDir = pc_prj.base_variant_dir
    v6_prj = None
else:
    print "***  Build for V6Z80P ..."
    #
    v6_prj = V6_Project()
    if  v6_prj.Init() == False:    
        Exit()
    v6_prj.SetupEnv()
    if v6_prj.checker.Init(v6_prj) == False:
        Exit()

    bdir = v6_prj.basedir

    variantBaseDir = v6_prj.base_variant_dir
    SConscript([bdir + '/c_support/crt/SConscript'],                  exports='v6_prj', variant_dir=variantBaseDir + '/c_support/crt/', duplicate=0)
    SConscript([bdir + '/c_support/os_interface_for_c/SConscript'],   exports='v6_prj', variant_dir=variantBaseDir + '/c_support/os_interface_for_c/', duplicate=0)
    SConscript([bdir + '/c_support/os_proxy/SConscript'],             exports='v6_prj', variant_dir=variantBaseDir + '/c_support/os_proxy/', duplicate=0)
    SConscript([bdir + '/c_support/stdio_v6z80p/SConscript'],         exports='v6_prj', variant_dir=variantBaseDir + '/c_support/stdio_v6z80p/', duplicate=0)
    SConscript([bdir + '/c_support/base_lib/SConscript'],         exports='v6_prj', variant_dir=variantBaseDir + '/c_support/base_lib/', duplicate=0)
      
  

            
# get all SConscript project files, in src/* dirs
files = Glob('src/*/SConscript')
#files = Glob('src/ciotry/SConscript')
for projectSconscript in files:
    #print projectSconscript
    projectDir = os.path.dirname(str(projectSconscript))
    #print projectDir
    projectName = os.path.split(projectDir)[1]
    #print projectName
    if Project_Helper.Is_Target_PC():
        SConscript([projectSconscript], exports='pc_prj', variant_dir=variantBaseDir + projectName, duplicate=0)
    else:
        SConscript([projectSconscript], exports='v6_prj', variant_dir=variantBaseDir + projectName, duplicate=0)
        
      
