# This is main SDCC framework configuration file. (scons file). When scons is started it will read this file.
import os
from  v6_project import V6_Project



#
v6_prj = V6_Project()
if  v6_prj.Init() == False:    
    Exit()
v6_prj.SetupEnv()
if v6_prj.checker.Init(v6_prj) == False:
    Exit()

bdir = v6_prj.basedir

variantBaseDir = v6_prj.base_variant_dir
SConscript([bdir + '/c_support/crt/SConscript'],                  exports='v6_prj', variant_dir=variantBaseDir + '/c_support/crt/', duplicate=0)
SConscript([bdir + '/c_support/os_interface_for_c/SConscript'],   exports='v6_prj', variant_dir=variantBaseDir + '/c_support/os_interface_for_c/', duplicate=0)
SConscript([bdir + '/c_support/os_proxy/SConscript'],             exports='v6_prj', variant_dir=variantBaseDir + '/c_support/os_proxy/', duplicate=0)
SConscript([bdir + '/c_support/stdio_v6z80p/SConscript'],         exports='v6_prj', variant_dir=variantBaseDir + '/c_support/stdio_v6z80p/', duplicate=0)
SConscript([bdir + '/c_support/base_lib/SConscript'],         exports='v6_prj', variant_dir=variantBaseDir + '/c_support/base_lib/', duplicate=0)
  
  

            
# get all SConscript project files, in src/* dirs
files = Glob('src/*/SConscript')
for projectSconscript in files:
    #print projectSconscript
    projectDir = os.path.dirname(str(projectSconscript))
    #print projectDir
    projectName = os.path.split(projectDir)[1]
    #print projectName
    SConscript([projectSconscript], exports='v6_prj', variant_dir=variantBaseDir + projectName, duplicate=0)
  
        
    

#projects = ['test0', 'test1',            'pong']   
#for prjName in projects:
#    SConscript(['src/' + prjName + '/SConscript'], exports='v6_prj', variant_dir='src/' + prjName + '/obj', duplicate=0)

