;---------------------------------------------------
; Full (official) Z80 instruction set test
;----------------------------------------------------

imm8	equ	$12	;comment
imm16	equ	$3456
addr	equ	$789a	;comment
disp	equ	48
port	equ	$c0	;comment

;----------------------------------------------------
	
	adc a,(hl)   	;comment
	adc a,(ix+disp)    	;comment
	adc a,(iy-disp)  	;comment
	adc a,a   	;comment
	adc a,b   	;comment
	adc a,c   	;comment
	adc a,d  		;comment
	adc a,e   	;comment
	adc a,h   	;comment
	adc a,l   	;comment
	adc a,imm8	;comment
	adc hl,bc   	;comment
	adc hl,de   	;comment
	adc hl,hl   	;comment
	adc hl,sp   	;comment
	add a,(hl)   	;comment
	add a,(ix+disp)    	;comment
	add a,(iy-disp)  	;comment
	add a,a   	;comment
	add a,b   	;comment
	add a,c   	;comment
	add a,d  		;comment
	add a,e   	;comment
	add a,h   	;comment
	add a,l   	;comment
	add a,imm8	;comment
	add hl,bc   	;comment
	add hl,de   	;comment
	add hl,hl   	;comment
	add hl,sp   	;comment
	add ix,bc   	;comment
	add ix,de   	;comment
	add ix,ix   	;comment
	add ix,sp   	;comment
	add iy,bc   	;comment
	add iy,de   	;comment
	add iy,iy		;comment
	add iy,sp   	;comment
	and (hl)   	;comment
	and (ix+disp)   	;comment
	and (iy-disp)  	;comment
	and a   		;comment
	and b   		;comment
	and c   		;comment
	and d  		;comment
	and e   		;comment
	and h   		;comment
	and l   		;comment
	and imm8		;comment
	bit 0,(hl)   	;comment
	bit 0,(ix+disp)   	;comment
	bit 0,(iy-disp)  	;comment
	bit 0,a   	;comment
	bit 0,b   	;comment
	bit 0,c   	;comment
	bit 0,d  		;comment
	bit 0,e   	;comment
	bit 0,h   	;comment
	bit 0,l   	;comment
	bit 1,(hl)   	;comment
	bit 1,(ix+disp)   	;comment
	bit 1,(iy-disp)  	;comment
	bit 1,a   	;comment
	bit 1,b   	;comment
	bit 1,c   	;comment
	bit 1,d  		;comment
	bit 1,e   	;comment
	bit 1,h   	;comment
	bit 1,l   	;comment
	bit 2,(hl)   	;comment
	bit 2,(ix+disp)   	;comment
	bit 2,(iy-disp)  	;comment
	bit 2,a   	;comment
	bit 2,b   	;comment
	bit 2,c   	;comment
	bit 2,d  		;comment
	bit 2,e   	;comment
	bit 2,h   	;comment
	bit 2,l   	;comment
	bit 3,(hl)   	;comment
	bit 3,(ix+disp)   	;comment
	bit 3,(iy-disp)  	;comment
	bit 3,a   	;comment
	bit 3,b   	;comment
	bit 3,c   	;comment
	bit 3,d  		;comment
	bit 3,e   	;comment
	bit 3,h   	;comment
	bit 3,l   	;comment
	bit 4,(hl)   	;comment
	bit 4,(ix+disp)   	;comment
	bit 4,(iy-disp)  	;comment
	bit 4,a   	;comment
	bit 4,b   	;comment
	bit 4,c   	;comment
	bit 4,d  		;comment
	bit 4,e   	;comment
	bit 4,h   	;comment
	bit 4,l   	;comment
	bit 5,(hl)   	;comment
	bit 5,(ix+disp)   	;comment
	bit 5,(iy-disp)  	;comment
	bit 5,a   	;comment
	bit 5,b   	;comment
	bit 5,c   	;comment
	bit 5,d  		;comment
	bit 5,e   	;comment
	bit 5,h   	;comment
	bit 5,l   	;comment
	bit 6,(hl)   	;comment
	bit 6,(ix+disp)   	;comment
	bit 6,(iy-disp)  	;comment
	bit 6,a   	;comment
	bit 6,b   	;comment
	bit 6,c   	;comment
	bit 6,d  		;comment
	bit 6,e   	;comment
	bit 6,h   	;comment
	bit 6,l   	;comment
	bit 7,(hl)   	;comment
	bit 7,(ix+disp)   	;comment
	bit 7,(iy-disp)  	;comment
	bit 7,a   	;comment
	bit 7,b   	;comment
	bit 7,c   	;comment
	bit 7,d  		;comment
	bit 7,e   	;comment
	bit 7,h   	;comment
	bit 7,l   	;comment
	call addr   	;comment
	call c,addr   	;comment
	call m,addr   	;comment
	call nc,addr   	;comment
	call nz,addr   	;comment
	call p,addr   	;comment
	call pe,addr   	;comment
	call po,addr   	;comment
	call z,addr   	;comment
	ccf   		;comment
	cp (hl)   	;comment
	cp (ix+disp)   	;comment
	cp (iy-disp)  	;comment
	cp a   		;comment
	cp b   		;comment
	cp c   		;comment
	cp d  		;comment
	cp e   		;comment
	cp h   		;comment
	cp l   		;comment
	cp imm8		;comment
	cpd 	 	;comment
	cpdr   		;comment
	cpi   		;comment
	cpir   		;comment
	cpl		;comment
	daa   		;comment
	dec (hl)   	;comment
	dec (ix+disp)   	;comment
	dec (iy-disp)  	;comment
	dec a   		;comment
	dec b   		;comment
	dec c   		;comment
	dec d  		;comment
	dec e   		;comment
	dec h   		;comment
	dec l   		;comment
	dec bc   		;comment
	dec de   		;comment
	dec hl 		;comment
	dec sp  		;comment
	dec ix   		;comment
	dec iy  		;comment
	di	   	;comment
	djnz $-2	  	;comment
	ei	   	;comment
	ex (sp),hl  	;comment
	ex (sp),ix  	;comment
	ex (sp),iy  	;comment
	ex af,af'  	;comment
	ex de,hl  	;comment
	exx	  	;comment
	halt	   	;comment
	im 0	   	;comment
	im 1  		;comment
	im 2  		;comment
	in a,(c)		;comment
	in b,(c)		;comment
	in c,(c)		;comment
	in d,(c)		;comment
	in e,(c)		;comment
	in h,(c)		;comment
	in l,(c)		;comment
	in a,(port)	;comment
	ind 	 	;comment
	indr   		;comment
	ini   		;comment
	inir   		;comment
	inc (hl)   	;comment
	inc (ix+disp)   	;comment
	inc (iy-disp)  	;comment
	inc a   		;comment
	inc b   		;comment
	inc c   		;comment
	inc d  		;comment
	inc e   		;comment
	inc h   		;comment
	inc l   		;comment
	inc bc   		;comment
	inc de   		;comment
	inc hl 		;comment
	inc sp  		;comment
	inc ix  		;comment
	inc iy 		;comment
	jp addr   	;comment
	jp (hl)		;comment
	jp (ix)		;comment
	jp (iy)		;comment
	jp c,addr   	;comment
	jp m,addr   	;comment
	jp nc,addr   	;comment
	jp nz,addr   	;comment
	jp p,addr   	;comment
	jp pe,addr   	;comment
	jp po,addr   	;comment
	jp z,addr   	;comment
	jr $-2		;comment
	jr c,$-2  	;comment
	jr nc,$-2 	;comment
	jr z,$-2  	;comment
	jr nz,$-2 	;comment
	ld a,a  	 	;comment
	ld a,b  	 	;comment
	ld a,c   		;comment
	ld a,d   		;comment
	ld a,e   		;comment
	ld a,h   		;comment
	ld a,l   		;comment
	ld b,a   		;comment
	ld b,b   		;comment
	ld b,c   		;comment
	ld b,d   		;comment
	ld b,e   		;comment
	ld b,h   		;comment
	ld b,l   		;comment
	ld c,a   		;comment
	ld c,b   		;comment
	ld c,c   		;comment
	ld c,d   		;comment
	ld c,e   		;comment
	ld c,h   		;comment
	ld c,l   		;comment
	ld d,a   		;comment
	ld d,b   		;comment
	ld d,c   		;comment
	ld d,d   		;comment
	ld d,e   		;comment
	ld d,h   		;comment
	ld d,l   		;comment
	ld e,a   		;comment
	ld e,b   		;comment
	ld e,c   		;comment
	ld e,d   		;comment
	ld e,e   		;comment
	ld e,h   		;comment
	ld e,l   		;comment
	ld h,a   		;comment
	ld h,b   		;comment
	ld h,c   		;comment
	ld h,d   		;comment
	ld h,e   		;comment
	ld h,h   		;comment
	ld h,l   		;comment
	ld l,a   		;comment
	ld l,b   		;comment
	ld l,c   		;comment
	ld l,d  		;comment
	ld l,e   		;comment
	ld l,h   		;comment
	ld l,l   		;comment
	ld i,a   		;comment
	ld r,a   		;comment
	ld a,i   		;comment
	ld a,r  		;comment
	ld a,(hl) 	;comment
	ld a,(ix+disp) 	;comment
	ld a,(iy-disp) 	;comment
	ld b,(hl) 	;comment
	ld b,(ix+disp)  	;comment
	ld b,(iy-disp)  	;comment
	ld c,(hl) 	;comment
	ld c,(ix+disp) 	;comment
	ld c,(iy-disp)  	;comment
	ld d,(hl) 	;comment
	ld d,(ix+disp)  	;comment
	ld d,(iy-disp) 	;comment
	ld e,(hl) 	;comment
	ld e,(ix+disp) 	;comment
	ld e,(iy-disp)  	;comment
	ld h,(hl) 	;comment
	ld h,(ix+disp)  	;comment
	ld h,(iy-disp)  	;comment
	ld l,(hl) 	;comment
	ld l,(ix+disp)  	;comment
	ld l,(iy-disp)  	;comment
	ld a,(bc) 	;comment
	ld a,(de) 	;comment
	ld a,(addr) 	;comment
	ld a,imm8		;comment
	ld b,imm8 	;comment
	ld c,imm8 	;comment
	ld d,imm8 	;comment
	ld e,imm8 	;comment
	ld h,imm8 	;comment
	ld l,imm8 	;comment
	ld (hl),a 	;comment
	ld (ix+disp),a  	;comment
	ld (iy-disp),a  	;comment
	ld (hl),b 	;comment
	ld (ix+disp),b  	;comment
	ld (iy-disp),b  	;comment
	ld (hl),c 	;comment
	ld (ix+disp),c  	;comment
	ld (iy-disp),c  	;comment
	ld (hl),d 	;comment
	ld (ix+disp),d  	;comment
	ld (iy-disp),d  	;comment
	ld (hl),e 	;comment
	ld (ix+disp),e  	;comment
	ld (iy-disp),e  	;comment
	ld (hl),h 	;comment
	ld (ix+disp),h  	;comment
	ld (iy-disp),h  	;comment
	ld (hl),l 	;comment
	ld (ix+disp),l  	;comment
	ld (iy-disp),l  	;comment
	ld (bc),a           ;comment
	ld (de),a           ;comment
	ld (addr),a   	;comment
	ld (hl),imm8   	;comment
	ld (ix+disp),imm8   ;comment
	ld (iy-disp),imm8   ;comment
	ld bc,imm16  	;comment
	ld de,imm16  	;comment
	ld hl,imm16  	;comment
	ld sp,imm16  	;comment
	ld ix,imm16  	;comment
	ld iy,imm16 	;comment
	ld bc,(addr)  	;comment
	ld de,(addr)  	;comment
	ld hl,(addr)  	;comment
	ld sp,(addr)  	;comment
	ld ix,(addr)  	;comment
	ld iy,(addr)  	;comment
	ld sp,hl  	;comment
	ld sp,ix   	;comment
	ld sp,iy   	;comment
	ld (addr),bc  	;comment
	ld (addr),de  	;comment
	ld (addr),hl  	;comment
	ld (addr),sp  	;comment
	ld (addr),ix  	;comment
	ld (addr),iy  	;comment
	ldi   		;comment
	ldir  		;comment
	ldd   		;comment
	lddr  		;comment
	neg   		;comment
	nop  		;comment
	or (hl)   	;comment
	or (ix+disp)   	;comment
	or (iy-disp)	;comment
	or a   		;comment
	or b   		;comment
	or c   		;comment
	or d  		;comment
	or e   		;comment
	or h   		;comment
	or l   		;comment
	or imm8		;comment
	out (c),a		;comment
	out (c),b		;comment
	out (c),c		;comment
	out (c),d		;comment
	out (c),e		;comment
	out (c),h		;comment
	out (c),l		;comment
	out (port),a	;comment
	outd 	 	;comment
	otdr   		;comment
	outi   		;comment
	otir   		;comment
	pop bc   		;comment
	pop de   		;comment
	pop hl   		;comment
	pop af   		;comment
	pop ix		;comment
	pop iy   		;comment
	push bc   	;comment
	push de   	;comment
	push hl   	;comment
	push af   	;comment
	push ix   	;comment
	push iy   	;comment
	res 0,(hl)   	;comment
	res 0,(ix+disp)   	;comment
	res 0,(iy-disp)  	;comment
	res 0,a   	;comment
	res 0,b   	;comment
	res 0,c   	;comment
	res 0,d  		;comment
	res 0,e   	;comment
	res 0,h   	;comment
	res 0,l   	;comment
	res 1,(hl)   	;comment
	res 1,(ix+disp)   	;comment
	res 1,(iy-disp)  	;comment
	res 1,a   	;comment
	res 1,b   	;comment
	res 1,c   	;comment
	res 1,d  		;comment
	res 1,e   	;comment
	res 1,h   	;comment
	res 1,l   	;comment
	res 2,(hl)   	;comment
	res 2,(ix+disp)   	;comment
	res 2,(iy-disp)  	;comment
	res 2,a   	;comment
	res 2,b   	;comment
	res 2,c   	;comment
	res 2,d  		;comment
	res 2,e   	;comment
	res 2,h   	;comment
	res 2,l   	;comment
	res 3,(hl)   	;comment
	res 3,(ix+disp)   	;comment
	res 3,(iy-disp)  	;comment
	res 3,a   	;comment
	res 3,b   	;comment
	res 3,c   	;comment
	res 3,d  		;comment
	res 3,e   	;comment
	res 3,h   	;comment
	res 3,l   	;comment
	res 4,(hl)   	;comment
	res 4,(ix+disp)   	;comment
	res 4,(iy-disp)  	;comment
	res 4,a   	;comment
	res 4,b   	;comment
	res 4,c   	;comment
	res 4,d  		;comment
	res 4,e   	;comment
	res 4,h   	;comment
	res 4,l   	;comment
	res 5,(hl)   	;comment
	res 5,(ix+disp)   	;comment
	res 5,(iy-disp)  	;comment
	res 5,a   	;comment
	res 5,b   	;comment
	res 5,c   	;comment
	res 5,d  		;comment
	res 5,e   	;comment
	res 5,h   	;comment
	res 5,l   	;comment
	res 6,(hl)   	;comment
	res 6,(ix+disp)   	;comment
	res 6,(iy-disp)  	;comment
	res 6,a   	;comment
	res 6,b   	;comment
	res 6,c   	;comment
	res 6,d  		;comment
	res 6,e   	;comment
	res 6,h   	;comment
	res 6,l   	;comment
	res 7,(hl)   	;comment
	res 7,(ix+disp)   	;comment
	res 7,(iy-disp)  	;comment
	res 7,a   	;comment
	res 7,b   	;comment
	res 7,c   	;comment
	res 7,d  		;comment
	res 7,e   	;comment
	res 7,h   	;comment
	res 7,l   	;comment
	ret	  	;comment
	ret c   		;comment
	ret m   		;comment
	ret nc   		;comment
	ret nz   		;comment
	ret p   		;comment
	ret pe   		;comment
	ret po   		;comment
	ret z   		;comment
	reti		;comment
	retn		;comment
	rl (hl)   	;comment
	rl (ix+disp)   	;comment
	rl (iy-disp)  	;comment
	rl a   		;comment
	rl b   		;comment
	rl c   		;comment
	rl d  		;comment
	rl e   		;comment
	rl h   		;comment
	rl l   		;comment
	rla		;comment
	rlc (hl)   	;comment
	rlc (ix+disp)   	;comment
	rlc (iy-disp)  	;comment
	rlc a   		;comment
	rlc b   		;comment
	rlc c   		;comment
	rlc d  		;comment
	rlc e   		;comment
	rlc h   		;comment
	rlc l   		;comment
	rlca		;comment
	rld		;comment
	rr (hl)   	;comment
	rr (ix+disp)   	;comment
	rr (iy-disp)  	;comment
	rr a   		;comment
	rr b   		;comment
	rr c   		;comment
	rr d  		;comment
	rr e   		;comment
	rr h   		;comment
	rr l   		;comment
	rra		;comment
	rrc (hl)   	;comment
	rrc (ix+disp)   	;comment
	rrc (iy-disp)  	;comment
	rrc a   		;comment
	rrc b   		;comment
	rrc c   		;comment
	rrc d  		;comment
	rrc e   		;comment
	rrc h   		;comment
	rrc l   		;comment
	rrca		;comment
	rrd		;comment
	rst $0   		;comment
	rst $8   		;comment
	rst $10		;comment
	rst $18   	;comment
	rst $20 		;comment
	rst $28   	;comment
	rst $30  		;comment
	rst $38  		;comment
	sbc a,(hl)   	;comment
	sbc a,(ix+disp)    	;comment
	sbc a,(iy-disp)  	;comment
	sbc a,a   	;comment
	sbc a,b   	;comment
	sbc a,c   	;comment
	sbc a,d  		;comment
	sbc a,e   	;comment
	sbc a,h   	;comment
	sbc a,l   	;comment
	sbc a,$10   	;comment
	sbc hl,bc   	;comment
	sbc hl,de   	;comment
	sbc hl,hl   	;comment
	sbc hl,sp   	;comment
	scf	  	;comment
	set 0,(hl)   	;comment
	set 0,(ix+disp)   	;comment
	set 0,(iy-disp)  	;comment
	set 0,a   	;comment
	set 0,b   	;comment
	set 0,c   	;comment
	set 0,d  		;comment
	set 0,e   	;comment
	set 0,h   	;comment
	set 0,l   	;comment
	set 1,(hl)   	;comment
	set 1,(ix+disp)   	;comment
	set 1,(iy-disp)  	;comment
	set 1,a   	;comment
	set 1,b   	;comment
	set 1,c   	;comment
	set 1,d  		;comment
	set 1,e   	;comment
	set 1,h   	;comment
	set 1,l   	;comment
	set 2,(hl)   	;comment
	set 2,(ix+disp)   	;comment
	set 2,(iy-disp)  	;comment
	set 2,a   	;comment
	set 2,b   	;comment
	set 2,c   	;comment
	set 2,d  		;comment
	set 2,e   	;comment
	set 2,h   	;comment
	set 2,l   	;comment
	set 3,(hl)   	;comment
	set 3,(ix+disp)   	;comment
	set 3,(iy-disp)  	;comment
	set 3,a   	;comment
	set 3,b   	;comment
	set 3,c   	;comment
	set 3,d  		;comment
	set 3,e   	;comment
	set 3,h   	;comment
	set 3,l   	;comment
	set 4,(hl)   	;comment
	set 4,(ix+disp)   	;comment
	set 4,(iy-disp)  	;comment
	set 4,a   	;comment
	set 4,b   	;comment
	set 4,c   	;comment
	set 4,d  		;comment
	set 4,e   	;comment
	set 4,h   	;comment
	set 4,l   	;comment
	set 5,(hl)   	;comment
	set 5,(ix+disp)   	;comment
	set 5,(iy-disp)  	;comment
	set 5,a   	;comment
	set 5,b   	;comment
	set 5,c   	;comment
	set 5,d  		;comment
	set 5,e   	;comment
	set 5,h   	;comment
	set 5,l   	;comment
	set 6,(hl)   	;comment
	set 6,(ix+disp)   	;comment
	set 6,(iy-disp)  	;comment
	set 6,a   	;comment
	set 6,b   	;comment
	set 6,c   	;comment
	set 6,d  		;comment
	set 6,e   	;comment
	set 6,h   	;comment
	set 6,l   	;comment
	set 7,(hl)   	;comment
	set 7,(ix+disp)   	;comment
	set 7,(iy-disp)  	;comment
	set 7,a   	;comment
	set 7,b   	;comment
	set 7,c   	;comment
	set 7,d  		;comment
	set 7,e   	;comment
	set 7,h   	;comment
	set 7,l   	;comment
	sla (hl)   	;comment
	sla (ix+disp)   	;comment
	sla (iy-disp)  	;comment
	sla a   		;comment
	sla b   		;comment
	sla c   		;comment
	sla d  		;comment
	sla e   		;comment
	sla h   		;comment
	sla l   		;comment
	sra (hl)   	;comment
	sra (ix+disp)   	;comment
	sra (iy-disp)  	;comment
	sra a   		;comment
	sra b   		;comment
	sra c   		;comment
	sra d  		;comment
	sra e   		;comment
	sra h   		;comment
	sra l   		;comment
	sra (hl)   	;comment
	srl (ix+disp)   	;comment
	srl (iy-disp)  	;comment
	srl a   		;comment
	srl b   		;comment
	srl c   		;comment
	srl d  		;comment
	srl e   		;comment
	srl h   		;comment
	srl l   		;comment
	sub (hl)   	;comment
	sub (ix+disp)    	;comment
	sub (iy-disp)  	;comment
	sub a 	  	;comment
	sub b   		;comment
	sub c   		;comment
	sub d  		;comment
	sub e  	 	;comment
	sub h   		;comment
	sub l   		;comment
	sub imm8		;comment
	xor (hl)   	;comment
	xor (ix+disp)    	;comment
	xor (iy-disp)  	;comment
	xor a   		;comment
	xor b   		;comment
	xor c   		;comment
	xor d  		;comment
	xor e   		;comment
	xor h   		;comment
	xor l   		;comment
	xor imm8		;comment
	
	end