# v6_prj - V6 Project object 
Import('v6_prj')

v6_prj.name     = 'test0'
v6_prj.linkopt  = '--code-loc 0x5A80 --data-loc 0'
v6_prj.stack    = '0xffff'
# v6_prj.heapsize = '0'

# There are total 3  environments : 
# 1. sdcc 2. pasmo 3. sdasz80

# In this project we need only sdcc environment  (to compile C source files)
env = v6_prj.env


# compile user .c files to oject files
objs = env.Object(   ['test0.c'], 
                CCFLAGS     = env['CCFLAGS']           + ['--std-sdcc99', '--opt-code-speed'],  
                CPPDEFINES  = env['CPPDEFINES']        + [{'OWN_SP' : v6_prj.stack}]
                )

# link and convert .ihx to .exe
final_exe = v6_prj.FLOS_Program(objs)

# here you can do something with final FLOS exe file (for example,  send it to V6 board)

# Create 'upload' target, to upload FLOS exe file to V6Z80P (via COM1, 'S0' - part of linux specific name ttyS0 of COM1)
# When exe file is re-builded, it will be send to the board.
upload = env.Alias('upload', final_exe, 'sendv6 S0 $SOURCE ');
upload[0].my_progress_message = '------------- Upload file to V6 -------------'



