SHELL = cmd.exe

#
# ZDS II Make File - test16colours project, Debug configuration
#
# Generated by: ZDS II - eZ80Acclaim! 5.1.1 (Build 10061702)
#   IDE component: d:5.1:10042301
#   Install Path: C:\Program Files\ZiLOG\ZDSII_eZ80Acclaim!_5.1.1\
#

RM = del

ZDS = C:\PROGRA~1\ZiLOG\ZDSII_~1.1
BIN = $(ZDS)\bin
# ZDS include base directory
INCLUDE = C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include
# intermediate files directory
WORKDIR = E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\16COLO~1\Debug

CC = @$(BIN)\eZ80cc
AS = @$(BIN)\eZ80asm
LD = @$(BIN)\eZ80link
AR = @$(BIN)\eZ80lib
WEBTOC = @$(BIN)\mkwebpage

ASFLAGS =  \
-define:_EZ80=1 -define:_SIMULATE=1  \
-include:"..;..\..\includes;$(INCLUDE)\std;$(INCLUDE)\zilog"  \
-list -NOlistmac -name -pagelen:56 -pagewidth:80 -quiet -sdiopt  \
-warn -debug -NOigcase -cpu:eZ80L92

LDFLAGS = @.\test16colours_Debug.linkcmd
OUTDIR = E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\16COLO~1\Debug

build: test16colours

buildall: clean test16colours

relink: deltarget test16colours

deltarget: 
	@if exist $(WORKDIR)\test16colours.lod  \
            $(RM) $(WORKDIR)\test16colours.lod
	@if exist $(WORKDIR)\test16colours.hex  \
            $(RM) $(WORKDIR)\test16colours.hex
	@if exist $(WORKDIR)\test16colours.map  \
            $(RM) $(WORKDIR)\test16colours.map

clean: 
	@if exist $(WORKDIR)\test16colours.lod  \
            $(RM) $(WORKDIR)\test16colours.lod
	@if exist $(WORKDIR)\test16colours.hex  \
            $(RM) $(WORKDIR)\test16colours.hex
	@if exist $(WORKDIR)\test16colours.map  \
            $(RM) $(WORKDIR)\test16colours.map
	@if exist $(WORKDIR)\16colourtest.obj  \
            $(RM) $(WORKDIR)\16colourtest.obj

# pre-4.11.0 compatibility
rebuildall: buildall 

LIBS = 

OBJS =  \
            $(WORKDIR)\16colourtest.obj

test16colours: $(OBJS)
	 $(LD) $(LDFLAGS)

$(WORKDIR)\16colourtest.obj :  \
            E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\16COLO~1\src\16colourtest.asm
	 $(AS) $(ASFLAGS) E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\16COLO~1\src\16colourtest.asm

