SHELL = cmd.exe

#
# ZDS II Make File - protracker project, Debug configuration
#
# Generated by: ZDS II - eZ80Acclaim! 5.1.1 (Build 10061702)
#   IDE component: d:5.1:10042301
#   Install Path: C:\Program Files\ZiLOG\ZDSII_eZ80Acclaim!_5.1.1\
#

RM = del

ZDS = C:\PROGRA~1\ZiLOG\ZDSII_~1.1
BIN = $(ZDS)\bin
# ZDS include base directory
INCLUDE = C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include
# intermediate files directory
WORKDIR = E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\PROTRA~3\Debug

CC = @$(BIN)\eZ80cc
AS = @$(BIN)\eZ80asm
LD = @$(BIN)\eZ80link
AR = @$(BIN)\eZ80lib
WEBTOC = @$(BIN)\mkwebpage

ASFLAGS =  \
-define:_EZ80=1 -define:_SIMULATE=1  \
-include:"E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\PROTRA~3;..\..\includes;$(INCLUDE)\std;$(INCLUDE)\zilog"  \
-list -NOlistmac -name -pagelen:56 -pagewidth:80 -quiet -sdiopt  \
-warn -debug -NOigcase -cpu:eZ80L92

LDFLAGS = @.\protracker_Debug.linkcmd
OUTDIR = E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\PROTRA~3\Debug

build: protracker

buildall: clean protracker

relink: deltarget protracker

deltarget: 
	@if exist $(WORKDIR)\protracker.lod  \
            $(RM) $(WORKDIR)\protracker.lod
	@if exist $(WORKDIR)\protracker.hex  \
            $(RM) $(WORKDIR)\protracker.hex
	@if exist $(WORKDIR)\protracker.map  \
            $(RM) $(WORKDIR)\protracker.map

clean: 
	@if exist $(WORKDIR)\protracker.lod  \
            $(RM) $(WORKDIR)\protracker.lod
	@if exist $(WORKDIR)\protracker.hex  \
            $(RM) $(WORKDIR)\protracker.hex
	@if exist $(WORKDIR)\protracker.map  \
            $(RM) $(WORKDIR)\protracker.map
	@if exist $(WORKDIR)\stereo_play.obj  \
            $(RM) $(WORKDIR)\stereo_play.obj

# pre-4.11.0 compatibility
rebuildall: buildall 

LIBS = 

OBJS =  \
            $(WORKDIR)\stereo_play.obj

protracker: $(OBJS)
	 $(LD) $(LDFLAGS)

$(WORKDIR)\stereo_play.obj :  \
            E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\PROTRA~3\src\stereo_play.asm  \
            E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\PROTRA~3\src\50Hz_Z80_Protracker_Player_v505.asm  \
            E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\PROTRA~3\src\Amiga_to_ez80p_audio_stereo.asm
	 $(AS) $(ASFLAGS) E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\PROTRA~3\src\stereo_play.asm

