SHELL = cmd.exe

#
# ZDS II Make File - rsky project, Debug configuration
#
# Generated by: ZDS II - eZ80Acclaim! 5.1.1 (Build 10061702)
#   IDE component: d:5.1:10042301
#   Install Path: C:\Program Files\ZiLOG\ZDSII_eZ80Acclaim!_5.1.1\
#

RM = del

ZDS = C:\PROGRA~1\ZiLOG\ZDSII_~1.1
BIN = $(ZDS)\bin
# ZDS include base directory
INCLUDE = C:\PROGRA~1\ZiLOG\ZDSII_~1.1\include
# intermediate files directory
WORKDIR = E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\RESET_~1\Debug

CC = @$(BIN)\eZ80cc
AS = @$(BIN)\eZ80asm
LD = @$(BIN)\eZ80link
AR = @$(BIN)\eZ80lib
WEBTOC = @$(BIN)\mkwebpage

ASFLAGS =  \
-define:_EZ80=1 -define:_SIMULATE=1  \
-include:"E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\RESET_~1;..\..\includes;$(INCLUDE)\std;$(INCLUDE)\zilog"  \
-list -NOlistmac -name -pagelen:56 -pagewidth:80 -quiet -sdiopt  \
-warn -debug -NOigcase -cpu:eZ80L92

LDFLAGS = @.\rsky_Debug.linkcmd
OUTDIR = E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\RESET_~1\Debug

build: rsky

buildall: clean rsky

relink: deltarget rsky

deltarget: 
	@if exist $(WORKDIR)\rsky.lod  \
            $(RM) $(WORKDIR)\rsky.lod
	@if exist $(WORKDIR)\rsky.hex  \
            $(RM) $(WORKDIR)\rsky.hex
	@if exist $(WORKDIR)\rsky.map  \
            $(RM) $(WORKDIR)\rsky.map

clean: 
	@if exist $(WORKDIR)\rsky.lod  \
            $(RM) $(WORKDIR)\rsky.lod
	@if exist $(WORKDIR)\rsky.hex  \
            $(RM) $(WORKDIR)\rsky.hex
	@if exist $(WORKDIR)\rsky.map  \
            $(RM) $(WORKDIR)\rsky.map
	@if exist $(WORKDIR)\ms_reset.obj  \
            $(RM) $(WORKDIR)\ms_reset.obj

# pre-4.11.0 compatibility
rebuildall: buildall 

LIBS = 

OBJS =  \
            $(WORKDIR)\ms_reset.obj

rsky: $(OBJS)
	 $(LD) $(LDFLAGS)

$(WORKDIR)\ms_reset.obj :  \
            E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\RESET_~1\src\ms_reset.asm
	 $(AS) $(ASFLAGS) E:\MY_OWN~1\Coding\EZ80PR~1\Code\PROSEA~1\RESET_~1\src\ms_reset.asm

